/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Warm-up / salud de la BD
         * @description Ejecuta un `SELECT 1` (con reintento) para despertar la BD Serverless y comprobar que responde. Sin identidad: no toca datos de usuario. El front lo llama fire-and-forget al empezar a grabar.
         */
        get: operations["healthDb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Configuración pública de autenticación (MSAL)
         * @description Config no secreta para inicializar MSAL en el frontend. Se necesita ANTES de autenticarse, por eso es pública. En local devuelve `{ devBypass: true }`: el front no monta MSAL ni gatea (espejo del bypass del middleware `identity`).
         */
        get: operations["getAuthConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leer configuración (API keys enmascaradas + proveedores disponibles) */
        get: operations["getConfig"];
        /**
         * Actualizar configuración (API keys / defaults)
         * @description Fusión superficial de `api_keys` y `defaults`. Devuelve la config enmascarada (nunca las claves en claro).
         */
        put: operations["updateConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar las sesiones del usuario (resumen) */
        get: operations["listSessions"];
        put?: never;
        /** Crear una sesión vacía */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** Leer una sesión completa (con segmentos) */
        get: operations["getSession"];
        /**
         * Actualizar columnas escalares de una sesión
         * @description Fusión superficial. Solo se escriben columnas en lista blanca (ver `SessionUpdate`); otras claves se ignoran. Los segmentos NO se gestionan aquí (van por /segments y /reprocess).
         */
        put: operations["updateSession"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** Uso + coste estimado de una sesión */
        get: operations["getSessionUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Añadir un segmento de audio (subir, transcribir, anexar)
         * @description Sube un audio (grabado o importado), lo normaliza (ffmpeg opcional), lo transcribe con el proveedor STT activo y lo añade como nuevo segmento; recalcula `transcription_raw` de la sesión.
         */
        post: operations["addSegment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Alias histórico de POST /sessions/{id}/segments
         * @description Idéntico a `/segments` (mismo handler). Se conserva por compatibilidad.
         */
        post: operations["transcribeSegment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/audio/{ordinal}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
                /** @description Posición 1-based del segmento dentro de la sesión. */
                ordinal: number;
            };
            cookie?: never;
        };
        /**
         * Descargar el audio de un segmento
         * @description Sirve el audio del segmento desde el almacén (contenedor privado en Azure); este es el único acceso autorizado al audio (no hay URL pública).
         */
        get: operations["getSegmentAudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-transcribir el audio ya guardado (rescate)
         * @description Re-transcribe los audios almacenados de la sesión y reproyecta `transcription_raw`. Rescata sesiones sin transcribir o mal transcritas.
         */
        post: operations["reprocessSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/distill": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Destilar la transcripción a un prompt
         * @description Destila `transcription_edited || transcription_raw` con el LLM activo. `mode` elige la variante (por defecto `completo`); `systemPrompt` opcional sobreescribe el prompt del modo solo para esta petición (no toca la BD).
         */
        post: operations["distillSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prompts por defecto de la familia del modelo activo
         * @description Devuelve `{ modo: texto }` de la familia del modelo LLM activo, para que el front los muestre y permita editarlos antes de destilar. Fuente: BD.
         */
        get: operations["getPrompts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar un lote de eventos de telemetría de captura
         * @description Best-effort: el cliente ignora los errores para no interrumpir la grabación. Máximo 200 eventos por lote; cada payload se trunca a ~8 KB.
         */
        post: operations["postDiagnostics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorDetail: {
            /** @description Código estable de error (p. ej. SESSION_NOT_FOUND, STT_FAILED). */
            code: string;
            /** @description Mensaje legible (puede variar; no es contrato). */
            message: string;
        };
        Error: {
            error: components["schemas"]["ErrorDetail"];
        };
        Segment: {
            /** @description Clave del audio en el almacén. */
            audio_file: string | null;
            transcription_raw: string | null;
            transcription_edited: string | null;
            duration_seconds: number | null;
            /** @enum {string} */
            source: "recorded" | "imported";
            /** @description ISO 8601. */
            created_at: string | null;
        };
        Session: {
            id: number;
            /** @description ISO 8601 de creación. */
            timestamp: string | null;
            segments: components["schemas"]["Segment"][];
            /** @description Vista materializada = concatenación del texto de los segmentos. */
            transcription_raw: string | null;
            transcription_edited: string | null;
            prompt_distilled: string | null;
            distill_mode: string | null;
            distill_prompt_used: string | null;
            llm_provider: string | null;
            llm_model: string | null;
            stt_provider: string | null;
            stt_model: string | null;
            /** @description Espejo legacy = audio del primer segmento. */
            audio_file: string | null;
        };
        SessionListItem: {
            id: number;
            timestamp: string | null;
            /** @description Primeros ~100 chars del prompt destilado o, si no, de la transcripción. */
            preview: string | null;
            has_prompt: boolean;
            has_transcription: boolean;
            has_audio: boolean;
            segment_count: number;
        };
        /** @description Columnas escalares actualizables (lista blanca). Todas opcionales; claves fuera de esta lista se ignoran en el backend. */
        SessionUpdate: {
            transcription_raw?: string | null;
            transcription_edited?: string | null;
            prompt_distilled?: string | null;
            distill_mode?: string | null;
            distill_prompt_used?: string | null;
            llm_provider?: string | null;
            llm_model?: string | null;
            stt_provider?: string | null;
            stt_model?: string | null;
        };
        UsageEvent: {
            id: number;
            /** @enum {string} */
            kind: "stt" | "llm";
            provider: string;
            model: string;
            input_tokens: number | null;
            output_tokens: number | null;
            audio_seconds: number | null;
            /** @description ISO 8601. */
            created_at: string;
        };
        Cost: {
            /** @example USD */
            currency: string;
            stt: number;
            llm: number;
            total: number;
            /** @description Nº de eventos sin tarifa conocida. */
            unpriced: number;
        };
        Usage: {
            events: components["schemas"]["UsageEvent"][];
            cost: components["schemas"]["Cost"];
        };
        /** @description API keys (enmascaradas en respuestas) + defaults de proveedor/modelo. */
        Config: {
            /** @description Clave por proveedor (enmascarada salvo últimos 4 chars). */
            api_keys: {
                anthropic?: string;
                groq?: string;
                google?: string;
                "azure-whisper"?: string;
                "azure-openai"?: string;
            } & {
                [key: string]: string;
            };
            defaults: {
                llm_provider: string;
                llm_model: string;
                stt_provider: string;
                stt_model: string;
            };
        };
        ConfigResponse: {
            config: components["schemas"]["Config"];
            llmProviders: string[];
            sttProviders: string[];
            configured: boolean;
        };
        /** @description Fusión superficial. Ambos campos opcionales. */
        ConfigUpdate: {
            api_keys?: {
                [key: string]: string;
            };
            defaults?: {
                [key: string]: string;
            };
        };
        AddSegmentForm: {
            /**
             * Format: binary
             * @description Audio del segmento (WebM/Opus u otro formato soportado).
             */
            audio: string;
            /**
             * @default recorded
             * @enum {string}
             */
            source: "recorded" | "imported";
        };
        AddSegmentResult: {
            segment: components["schemas"]["Segment"];
            /** @description Transcripción de sesión recalculada tras añadir el segmento. */
            transcription_raw: string;
            session: components["schemas"]["Session"];
        };
        ReprocessResult: {
            transcription_raw: string;
            session: components["schemas"]["Session"];
        };
        DistillRequest: {
            /**
             * @description Ausente o desconocido → el backend resuelve a `completo`.
             * @enum {string}
             */
            mode?: "completo" | "ligero" | "literal" | "limpio";
            /** @description Override del prompt del modo, solo para esta petición. */
            systemPrompt?: string;
        };
        /** @description Uso de tokens del LLM (forma dependiente del proveedor). */
        LlmUsage: {
            input_tokens?: number;
            output_tokens?: number;
        } | null;
        DistillResult: {
            prompt_distilled: string;
            usage: components["schemas"]["LlmUsage"];
            truncated: boolean;
            session: components["schemas"]["Session"];
        };
        /** @description Mapa modo→texto de prompt de la familia del modelo activo. */
        FamilyPrompts: {
            [key: string]: string;
        };
        /** @description Evento de telemetría de captura. El backend descarta los que no traen `type` + `captureRunId`. */
        DiagnosticEvent: {
            captureRunId: string;
            type: string;
            seq?: number;
            payload?: {
                [key: string]: unknown;
            };
            clientTs?: number | string;
            sessionId?: number;
        };
        /** @description Bypass local, o parámetros MSAL en Azure. */
        AuthConfig: {
            /** @constant */
            devBypass: true;
        } | {
            clientId: string | null;
            authority: string;
            apiScope: string | null;
        };
    };
    responses: {
        /** @description Falta token (UNAUTHENTICATED) o token inválido/expirado (TOKEN_INVALID). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Cuenta no autorizada (NOT_ALLOWLISTED). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Sesión no encontrada (SESSION_NOT_FOUND). Incluye recursos de otro propietario (aislamiento). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Error interno. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Identificador entero de la sesión. */
        SessionId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthDb: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La BD responde. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                    };
                };
            };
            /** @description La BD no está disponible. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: false;
                        error?: components["schemas"]["ErrorDetail"];
                    };
                };
            };
        };
    };
    getAuthConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config de auth (bypass local, o parámetros MSAL en Azure). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfig"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuración actual. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["ServerError"];
        };
    };
    updateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdate"];
            };
        };
        responses: {
            /** @description Config actualizada (enmascarada). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        config: components["schemas"]["Config"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["ServerError"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de sesiones (más recientes primero). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListItem"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["ServerError"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión creada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["ServerError"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Sesión actualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getSessionUsage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eventos de uso y desglose de coste (estimado). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    addSegment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AddSegmentForm"];
            };
        };
        responses: {
            /** @description Segmento añadido. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddSegmentResult"];
                };
            };
            /** @description Falta audio (MISSING_AUDIO) o falta API key del STT (MISSING_API_KEY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Fallo de transcripción (STT_FAILED). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    transcribeSegment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AddSegmentForm"];
            };
        };
        responses: {
            /** @description Segmento añadido. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddSegmentResult"];
                };
            };
            /** @description MISSING_AUDIO o MISSING_API_KEY. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description STT_FAILED. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSegmentAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
                /** @description Posición 1-based del segmento dentro de la sesión. */
                ordinal: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audio del segmento. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/webm": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Sesión (SESSION_NOT_FOUND) o audio (AUDIO_NOT_FOUND) no encontrados. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Fallo al servir el audio (AUDIO_FAILED). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    reprocessSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión reprocesada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReprocessResult"];
                };
            };
            /** @description Falta API key (MISSING_API_KEY) o no hay audio (NO_AUDIO). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description STT_FAILED. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    distillSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador entero de la sesión. */
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DistillRequest"];
            };
        };
        responses: {
            /** @description Prompt destilado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistillResult"];
                };
            };
            /** @description Sin transcripción (NO_TRANSCRIPTION), modelo deshabilitado (MODEL_DISABLED) o falta API key (MISSING_API_KEY). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Fallo del LLM (LLM_FAILED). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPrompts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mapa modo→prompt de la familia activa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyPrompts"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["ServerError"];
        };
    };
    postDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    events: components["schemas"]["DiagnosticEvent"][];
                };
            };
        };
        responses: {
            /** @description Eventos insertados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        inserted: number;
                    };
                };
            };
            /** @description Falta el array o ningún evento válido (BAD_REQUEST). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Demasiados eventos por lote (TOO_LARGE, máximo 200). */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No se pudieron guardar (DIAG_FAILED). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
